FROM golang:1.22 AS builder

WORKDIR /go/src/github.com/abdvswmdr/soqonicatalogue

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/main ./cmd/cataloguesvc

FROM alpine:3.19

ENV SERVICE_USER=myuser \
    SERVICE_UID=10001 \
    SERVICE_GROUP=mygroup \
    SERVICE_GID=10001

RUN addgroup -g ${SERVICE_GID} ${SERVICE_GROUP} && \
    adduser -g "catalogue user" -D -H -G ${SERVICE_GROUP} -s /sbin/nologin -u ${SERVICE_UID} ${SERVICE_USER}

WORKDIR /
COPY --from=builder /app/main /app
COPY images/ /images/

RUN chown -R ${SERVICE_USER}:${SERVICE_GROUP} /app /images

USER ${SERVICE_USER}

EXPOSE 80

CMD ["/app", "-port=80"]
